### ISSUE TITLE
Ingestion of matrices with duplicate rownames throws error.

### ISSUE THREAD

**Issue by dkdeconti** [web-mev/mev-backend#18]
Matrices with duplicate rownames throw an error. A sane approach to resolving the error or providing the problematic rownames is needed.

**Comment by blawney** [comment]
Raising this from the dead...

Currently we reject these files and warn the user about duplicate row names.

I'm concerned that adding some logic to unique'ify the names will introduce unexpected issues. 

For instance, if the second occurrence of (duplicated) feature X is the "interesting" one, then we risk renaming it to e.g. "X_1" and losing any ability to find that feature in gene databases, etc. It seems like it's safer/best to reject and warn the user. They can then modify the file themselves (AKA give them their own rope...)

**Comment by blawney** [comment]
cleaning this up. We simply reject duplicate row names and let the user handle it. This has been in the test suite for a while now.
