### ISSUE TITLE
Files used in an analysis cannot be removed from a workspace despite an error sent back when used in an analysis.

### ISSUE THREAD

**Issue by dkdeconti** [web-mev/mev-backend#40]
When uploaded a CSV limma file produced locally, the column names did not match the expected from fgsea. Specifically, the uploaded column had "P.Value" as a column name, not recognized by fgsea. Upon attempting to delete this file, for a clean workspace when uploading a fixed CSV, was given a warning about unable to remove files used in an analysis.

**Comment by blawney** [comment]
Added in 5759257ed0c09c84bab1abe76894358cdce1983c
